// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";
import * as Index from "../src/Index.mjs";

Zora.test("should run a test synchronously", (function (t) {
        t.equal(3.14, 3.14, "Should be a tasty dessert");
        
      }));

Zora.test("", (function (t) {
        var a = Index.lexing("rstar[atrsaon[url]aorsinit[/url][]]rasta");
        console.log(a);
        t.equal(1, 1, "");
        
      }));

export {
  
}
/*  Not a pure module */
