// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "zora";
import * as Bbcode from "../src/bbcode.mjs";

Zora.test("digit parser", (function (t) {
        var a = Bbcode.Parse.run("[tag]", Bbcode.Parse.bbcodetag);
        t.equal(a, "tag", "");
        
      }));

export {
  
}
/*  Not a pure module */
