// Generated by ReScript, PLEASE EDIT WITH CARE

import * as BBCodeInternal from "./BBCodeInternal.mjs";

var parse = BBCodeInternal.parse;

export {
  parse ,
  
}
/* BBCodeInternal Not a pure module */
