// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function Stub(Props) {
  var a = Props.a;
  var f = Props.f;
  switch (a.TAG | 0) {
    case /* Text */0 :
        return React.createElement("span", {
                    className: "bbcode"
                  }, a._0);
    case /* Link */14 :
    case /* Image */16 :
    case /* ImageResized */17 :
    case /* List */18 :
    case /* Table */22 :
    case /* YouTube */24 :
        break;
    default:
      return React.createElement("div", {
                  className: "bbcode"
                }, Curry._1(f, a.children));
  }
  return React.createElement("div", {
              className: "bbcode"
            });
}

var make = Stub;

export {
  make ,
  
}
/* react Not a pure module */
